name: his_mobile
description: "Mobile Application for Health Information System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  get_it: ^7.6.6
  dio: ^5.4.1
  json_serializable: ^6.7.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  animated_toggle_switch: ^0.8.0
  flutter_localization: ^0.2.0
  intl: any
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  dartz: ^0.10.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/vectors/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700